#! /usr/bin/env ruby

VERSION = "1.0.0"
DEFAULT_CONFIG = '~/.dod/config.yml'

require 'slop'
require 'net/ping'
require 'tplink_smarthome_api'
require 'yaml'

require_relative 'lib/utils'
require_relative 'lib/helpers'
include Utils
include Helpers

opts = Slop.parse do |o|
  o.separator ''
  o.separator 'Optional:'
  o.string  '-c', '--config', "Path to your config file. Default: #{DEFAULT_CONFIG}", required: false, default: DEFAULT_CONFIG
  o.separator ''
  o.separator 'Other:'

  o.on '-v', '--version' do
    puts VERSION ; exit
  end

  o.on '--help' do
    puts o ; exit
  end
end

unless File.exist?(File.expand_path(opts[:config]))
  puts "File not found: #{opts[:config]}"
  exit 1
end

loop do
  config = YAML.load_file(File.expand_path(opts[:config]))
  config['checks'].each do |c|
    puts "[#{Time.now}] Running '#{check_name(c)}'"

    if run_command!(c['check'])
      log_and_run!("[#{Time.now}] * SUCCESS", c['on_success'])
    else
      log_and_run!("[#{Time.now}] * FAILURE", c['on_failure'])
    end
  end

  interval = config['interval'] || 60
  puts "[#{Time.now}] Sleeping for #{interval} seconds..."
  sleep interval
end
